# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FSCalendarPractice' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'FSCalendar', :git => 'https://github.com/hyejinL/FSCalendar.git', :branch => 'dooribun'
  # Pods for FSCalendarPractice

end
